---
- name: Make sure required services are running
  systemd:
    state: started
    name: "{{ item }}"
  with_items:
    - docker

- name: Create directory for Docker build
  file:
    path: /home/core/rebuilderd-worker-vm
    state: directory
    mode: '0755'

- name: Copy Dockerfile and entrypoint script
  copy:
    src: entrypoint.sh
    dest: /home/core/rebuilderd-worker-vm/{{ item }}
    owner: core
    mode: 0644
  notify:
    - Build rebuilderd worker vm docker image
  with_items:
    - 'Dockerfile'
    - 'entrypoint.sh'
    - 'rebuilderd-worker.conf'

- name: Copy rebuilderd-worker-vm service files
  copy:
    src: "{{ item.service }}"
    dest: /etc/systemd/system/{{ item.service }}
    owner: core
    mode: 0644
  notify: "{{ item.notify }}"
  with_items:
    - { service: 'rebuilderd-worker-vm@.service', notify: ['Restart rebuilderd workers'] }

- name: Start rebuilderd workers
  systemd:
    name: rebuilderd-worker-vm@0
    enabled: true
    state: started
    daemon-reload: true
