---
- name: Restart rebuilderd workers
  systemd:
    name: rebuilderd-worker-vm@0
    enabled: true
    state: restarted
    daemon-reload: true

- name: Build rebuilderd worker vm docker image
  docker_image:
    build:
      path: /home/core/rebuilderd-worker-vm
    name: rebuilderd-woker-vm
    source: build
